### PR TITLE
fix for multi-hop messages

### PR DESCRIPTION
**Pull request by Jordo-o**
See issue https://github.com/GermanCoding/Roundcube_TLS_Icon/issues/13

### CODE REVIEW

**Comment by Jordo-o** [comment]
Wrong commit, please remove this pull-request if possible :)

**Comment by Jordo-o** [comment]
Wrong commit, pull-request can be removed

**Comment by williamdes** [comment]
> Wrong commit, pull-request can be removed

You can not delete a pull-request, if you want to delete it's content you need to do a force push to remove the commits
and it will also auto close the PR since the diff will be null
once the branch deleted except if you can restore it and re open the PR will stay as it is

**Comment by Jordo-o** [comment]
I have already deleted the branche, so then we just leave it closed.
It's not really a big problem, I just thought, let's clean it up if possible :)

**Pull request closed without merging**
